// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALQvKijssp4oUmZdAgEXZNMuzhmNx6YEE',
    appId: '1:198986442579:web:8eb1ff7a18e4b9288ea3a6',
    messagingSenderId: '198986442579',
    projectId: 'tafheel-creation',
    authDomain: 'tafheel-creation.firebaseapp.com',
    storageBucket: 'tafheel-creation.firebasestorage.app',
    measurementId: 'G-R61VVEV7TM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADXptW1_nR_-8gSTZsMudGxb3DEdhTvPo',
    appId: '1:198986442579:android:e1c6d068c4f82d7e8ea3a6',
    messagingSenderId: '198986442579',
    projectId: 'tafheel-creation',
    storageBucket: 'tafheel-creation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5tEOyyDUMFoU4QtfawaVBQTH_R2_gCWY',
    appId: '1:198986442579:ios:c5dc04db28c36c758ea3a6',
    messagingSenderId: '198986442579',
    projectId: 'tafheel-creation',
    storageBucket: 'tafheel-creation.firebasestorage.app',
    iosClientId: '198986442579-dmblh0psecqrbosr02034la9uqplce9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.tafheelDocs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5tEOyyDUMFoU4QtfawaVBQTH_R2_gCWY',
    appId: '1:198986442579:ios:c5dc04db28c36c758ea3a6',
    messagingSenderId: '198986442579',
    projectId: 'tafheel-creation',
    storageBucket: 'tafheel-creation.firebasestorage.app',
    iosClientId: '198986442579-dmblh0psecqrbosr02034la9uqplce9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.tafheelDocs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALQvKijssp4oUmZdAgEXZNMuzhmNx6YEE',
    appId: '1:198986442579:web:6a016128fa260ec28ea3a6',
    messagingSenderId: '198986442579',
    projectId: 'tafheel-creation',
    authDomain: 'tafheel-creation.firebaseapp.com',
    storageBucket: 'tafheel-creation.firebasestorage.app',
    measurementId: 'G-NNK4EJTKXX',
  );
}
